### ISSUE TITLE
Fail to compile on FreeBSD: module "MeuiKit" is not installed

### ISSUE THREAD

**Issue by probonopd** [cyberos/cyber-dock#10]
```
FreeBSD:/home/user/cyber-dock/build% ./cyber-dock
QKqueueFileSystemWatcherEngine::addPaths: open: No such file or directory
qrc:/qml/main.qml:5:1: module "MeuiKit" is not installed 
     import MeuiKit 1.0 as Meui 
     ^

FreeBSD:/home/user/cyber-dock/build% ls /usr/lib/qt/qml/MeuiKit
Icon.qml        PopupTips.qml   RoundedRect.qml Units.qml
libMeuiKit.so   qmldir          Theme.qml
```

I had used 

```
FreeBSD:/home/user/meuikit/build% cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local ..
```

but the files are in `/usr/lib/qt/qml`. On FreeBSD they should be in `/usr/local/lib/qt/qml`...

**Comment by probonopd** [comment]
Workaround: `sudo mv /usr/lib/qt/qml/MeuiKit /usr/local/lib/qt5/qml/`

The issue should probably be moved to https://github.com/cyberos/meuikit/issues

**Comment by reionwong** [comment]
@omaemae

**Comment by reionwong** [comment]
https://github.com/cyberos/cyber-fm/issues/1

**Comment by probonopd** [comment]
So I need to modify the `INSTALL_QMLDIR` variable of Meuikit's CMakeLists.txt?

```
set(INSTALL_QMLDIR /usr/local/lib/qt5/qml/)
```

Or is there a way for Qt to detect the correct directory automatically?

**Comment by reionwong** [comment]
I found a way to get the directory of qml, find the correct directory through `qmake`:

```
qmake -query QT_INSTALL_QML
```

**Comment by probonopd** [comment]
I can confirm that this works for me:

```
FreeBSD:/home/user% qmake -query QT_INSTALL_QML
/usr/local/lib/qt5/qml
```
