### ISSUE TITLE
Left mode breaks the new dock style completely

### ISSUE THREAD

**Issue by itsvic-dev** [cyberos/cyber-dock#11]
![image](https://user-images.githubusercontent.com/17727163/106966642-04277b00-6746-11eb-84cc-10b683f6e013.png)

**Comment by reionwong** [comment]
I got it

**Comment by reionwong** [comment]
https://github.com/cyberos/cyber-dock/commit/d77e301e57bf1a2edb3a694983ad35fb96697a8b
