### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by sonichy** [cyberos/cyber-dock#13]
### Ubuntu Kylin 20.04.2

```
Could not find a package configuration file provided by "Qt5Quick" with any of the following names:
    Qt5QuickConfig.cmake
    qt5quick-config.cmake
```    
sudo apt install qtdeclarative5-dev

```
Could not find a package configuration file provided by "Qt5QuickControls2" with any of the following names:
    Qt5QuickControls2Config.cmake
    qt5quickcontrols2-config.cmake
```    
sudo apt install qtquickcontrols2-5-dev

```
Could not find a package configuration file provided by "Qt5X11Extras" with any of the following names:
    Qt5X11ExtrasConfig.cmake
    qt5x11extras-config.cmake
```    
sudo apt install libqt5x11extras5-dev

```
Could not find a package configuration file provided by "KF5WindowSystem" with any of the following names:
    KF5WindowSystemConfig.cmake
    kf5windowsystem-config.cmake
```    
sudo apt install libkf5windowsystem-dev

```
Could not find a package configuration file provided by "dbusmenu-qt5" with any of the following names:
    dbusmenu-qt5Config.cmake
    dbusmenu-qt5-config.cmake
```    
sudo apt install libdbusmenu-qt5-dev

```
Could not find a package configuration file provided by "MeuiKit" with any of the following names:
    MeuiKitConfig.cmake
    meuikit-config.cmake
```
install syberos/meuikit

```
include could not find load file:
    ECMGenerateHeaders
```    
sudo apt install extra-cmake-modules

```
xcb/shape.h: no such file or directory
    #include <xcb/shape.h>
```    
sudo apt install libxcb-shape0-dev

`qml module "QtGraphicalEffects" version 1.15 is not installed`
sudo apt install qml-module-qtgraphicaleffects useless

![alt](https://s3.ax1x.com/2021/02/13/ysmnSg.png)
No icon only blur background.

**Comment by itsvic-dev** [comment]
You also need to install `libcyber-system`. Apologies!

**Comment by sonichy** [comment]
After installed libcyber-system, still the same !

**Comment by itsvic-dev** [comment]
Does the Dock throw any exception about not being able to find a module?

**Comment by itsvic-dev** [comment]
Actually yes, it does:
![image](https://user-images.githubusercontent.com/17727163/107855730-53476d00-6e24-11eb-85f2-9ee88647d0a8.png)

It's caused by Ubuntu not having the latest Qt 5.15.2, which Cyber heavily depends on, so you need to compile it yourself.
