### ISSUE TITLE
Use QStandardPaths instead of /usr/share/applications

### ISSUE THREAD

**Issue by probonopd** [cyberos/cyber-dock#19]
Instead of hardcoding one path

https://github.com/cyberos/cyber-dock/blob/364b19066669da09dfa15440d3b06d3f4e2ed655/src/systemappmonitor.cpp#L28

we should use 

[`QStandardPaths::ApplicationsLocation`](https://doc.qt.io/qt-5/qstandardpaths.html) which can have more than one path, and can have different paths on different systems.

For example, in addition to `/usr/share/applications` there is usually also `~/.local/share/applications"`, and FreeBSD uses `/usr/local/share/applications`.

Reference: https://github.com/helloSystem/ISO/issues/114#issuecomment-796920251

**Comment by itsvic-dev** [comment]
This shouldn't be hard, as far as I can tell.
```
test: ("/home/omame/.local/share/applications", "/usr/local/share/applications", "/usr/share/applications")
```
```cpp
qDebug() << "test:" << QStandardPaths::standardLocations(QStandardPaths::ApplicationsLocation);
```

**Comment by itsvic-dev** [comment]
I've also noticed cyber-launcher using similar code here:
https://github.com/cyberos/cyber-launcher/blob/main/src/launchermodel.cpp#L51

One more thing to deal with.

**Comment by probonopd** [comment]
Thanks @omaemae, this is working well for me.
