### ISSUE TITLE
Autohide the dock

### ISSUE THREAD

**Issue by woomia** [cyberos/cyber-dock#25]
Can the dock be autohidden? It takes up a a lot of real estate I need. Here are links to how ksmoothdock does its autohide.

ksmoothdock has a lot of KDE depends BUT this where the autohide code lives:
https://github.com/dangvd/ksmoothdock/blob/master/src/view/dock_panel.cc
https://github.com/dangvd/ksmoothdock/blob/master/src/view/dock_panel.h

**Comment by probonopd** [comment]
I am also interested in this. (Should be optional.)

**Comment by woomia** [comment]
As a temporary fix, can the Dock be decoupled from the session? I tried xkill on it to install my own dock but it crashed the whole session, logging me out. If this can be done, It would be a nice work around.

**Comment by reionwong** [comment]
https://github.com/cutefishos/dock
Already done

**Comment by woomia** [comment]
"already done", okay, cool, then how do I get it to autohide?

**Comment by reionwong** [comment]
In CutefishOS, by settings app.

**Comment by woomia** [comment]
I'm using it on HelloSystem, there is a text file I can edit instead?

**Comment by probonopd** [comment]
The dock in helloSystem is based on an older version, it doesn't have this feature yet.
