### ISSUE TITLE
Allow to set icon using path to icon file

### ISSUE THREAD

**Issue by probonopd** [cyberos/cyber-dock#3]
Allow to set icon using path to icon file, not just from the current icon theme.

In `.desktop files`, both of these work:

`Icon=/usr/local/share/chromium/product_logo_48.png` (takes the icon from the specified file)

and

`Icon=chromium-browser` (takes the icon from the icon theme)

Use case: I would set some icons to use the icon that came with the application, not the icon that came with the theme. Also, the theme does not have any icon for some applications.

**Comment by reionwong** [comment]
It can be customized, you need to edit the dock configuration file: ~/.config/cyberos/dock_pinned.conf

just like:
```
[Chromium]
DesktopPath=
Exec=/usr/bin/chromium
IconName=file:///home/reven/Desktop/icons.jpg
Index=3
visibleName=Chromium
```

![Screenshot from 2020-10-20 09-04-37](https://user-images.githubusercontent.com/9636382/96527746-7f5a4380-12b3-11eb-8ce1-d33bd5598787.png)

**Comment by probonopd** [comment]
Thank you. Very good. I did not know that I have to use `file://`.
