### ISSUE TITLE
Build fails, new dependency on Wayland library

### ISSUE THREAD

**Issue by probonopd** [cyberos/cyber-dock#4]
Build fails due to new undocumented dependency on Wayland library:

https://cirrus-ci.com/task/5946490726121472?command=test#L28

It would be good if Wayland support was an __optional__ build-time option, so that we can build without Wayland dependencies if we are not interested in Wayland.

**Comment by reionwong** [comment]
I think adding kwayland dependence can be solved, there is no adaptation to wayland yet, it can be removed
