### ISSUE TITLE
[Feature request] Allow for Window minimization animation

### ISSUE THREAD

**Issue by probonopd** [cyberos/cyber-dock#5]
Allow for Window minimization animation like this one:
https://twitter.com/omgubuntu/status/1321847967549194241

Is this something cyber-dock needs to support, or is it just a feature of the window manager?

**Comment by reionwong** [comment]
This is something that cyber-dock needs to support. It needs to tell the window manager the location of each icon. 

I haven't implemented it yet, I have other work :)

panda-dock is implemented like this: 
https://github.com/pandaos/panda-dock/blob/master/item/appitem.cpp#L124

**Comment by reionwong** [comment]
try again :)

**Comment by probonopd** [comment]
Thank you very much. Which window manager(s) do I need?

**Comment by reionwong** [comment]
I am using KWin, you should choose a window manager with compositing effects.
