### ISSUE TITLE
[Feature request] Allow drag-and-drop

### ISSUE THREAD

**Issue by probonopd** [cyberos/cyber-dock#6]
Allow drag-and-drop of applications into the Dock:

https://www.youtube.com/watch?v=E1MAXftilSs

**Comment by reionwong** [comment]
this is the future of support

**Comment by probonopd** [comment]
Thank you. Does the file manager need to do something special? I am getting `qrc:/qml/AppItem.qml:28: TypeError: Cannot read property 'dragItemIndex' of null`:

https://user-images.githubusercontent.com/2480569/102696193-c66da200-422c-11eb-9cf3-b6d18a9a1234.mp4

Nothing happens when I drag a txt file between existing icons (it should add the txt file to the Dock). Also, nothing happens when I drag the txt file over the text editor app (it should open the txt file with the text editor app).

I am using https://github.com/helloSystem/Filer/ as the file manager. Does the file manager need to implement something special to support this?

Thank you very much for your support.

**Comment by reionwong** [comment]
You can refer to the documentation: https://doc.qt.io/qt-5/qml-qtquick-dragevent.html

just like:

```qml
dropArea.onEntered: {
    if (drag.source.dragItemIndex)
        appModel.move(drag.source.dragItemIndex, dragItemIndex)

    if (drag.hasUrls) {
        // do something
    }
}
```
